spring:
  profiles:
    active: local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      auto-commit: true
      idle-timeout: 30000
      pool-name: DatebookHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: select 1
  redis:
    timeout: 3000
    lettuce:
      pool:
        max-idle: 10
        min-idle: 0
        max-active: 10
        max-wait: 1000
mybatis:
  mapper-locations: classpath:mappers/*/*.xml
security:
  oauth2:
    token:
      store:
        type: jwt
check-user-scopes: true
logging:
  level:
    root: info
