spring:
  datasource:
    url: jdbc:mysql://rm-uf6zxqtxvj788nzrazo.mysql.rds.aliyuncs.com:3306/story?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull
    username: super_root
    password: 1zhida**
logging:
  level:
    com.story.code: debug